name: PlotSystem
main: galaxygamer088\PlotSystem\PlotSystem
author: galaxygamer088
authors:
  - DemonicDev \\ Tijmen2004 ==> bump to API 5 (ver 2.0.0-alpha)
description: An Advanced CityBuild Plugin made by galaxygamer088.
version: 2.0.0
api: 5.0.0
commands:
  
  p:
    description: PlotSystem
    permission: "plot.player"

permissions:
  plot.player:
    default: true

  plot.op:
    default: op